---
title: Stackbit Starter Theme
baseURL: "/"
params:
  description: An ultra customizable generic theme for Stackbit
  header:
    type: header
    template: header
    title: Starter
    has_nav: true
    nav_links:
    - type: action
      template: action
      label: Features
      url: "/features"
      style: link
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Blog
      url: "/blog"
      style: link
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: About
      url: "/about"
      style: link
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Style Guide
      url: "/style-guide"
      style: link
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Contact Us
      url: "/contact"
      style: primary
      new_window: false
      no_follow: false
    logo: "/images/ark-large.png"
    logo_alt: arkgroup
  footer:
    type: footer
    template: footer
    has_nav: true
    nav_links:
    - type: action
      template: action
      label: Contact Us
      url: "/contact"
      style: link
      new_window: false
      no_follow: false
    - type: action
      template: action
      label: Privacy and Terms
      url: "/terms"
      style: link
      new_window: false
      no_follow: false
    has_social: true
    social_links:
    - type: action
      template: action
      label: Twitter
      url: https://twitter.com/
      style: link
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: GitHub
      url: https://github.com/
      style: link
      new_window: true
      no_follow: false
    - type: action
      template: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: link
      new_window: true
      no_follow: false
    content: ''
    links: []
  favicon: ''
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
uglyURLs: false
